#!/usr/bin/env python3
import os
import sys
from analyzer import Analyzer
from termcolor import colored
import helpers

def main():
    if len(sys.argv) != 2:
        print("program must take exactly 1 console arg!")
        return 0
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    tweets = helpers.get_user_timeline(sys.argv[1], 50)
    
    for tweet in tweets:
        # analyze word
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(score, colored(tweet, "green"))
        elif score < 0.0:
            print(score, colored(tweet, "red"))
        else:
            print(score, colored(tweet, "yellow"))
    
    
if __name__ == "__main__":
    main()